version = 0.1
[default.deploy.parameters]
stack_name = "react-cognito"
resolve_s3 = true
s3_prefix = "react-cognito"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"awsome19095-static-site\" CognitoUserPoolName=\"awsome-userpool\" CognitoWebClientName=\"awsome-webclient\""
image_repositories = []
