/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsExports = {
    "aws_project_region": "ap-south-1",
        "REGION": "ap-south-1",
        "USER_POOL_ID": "ap-south-1_tiTtQFXgV",
        "USER_POOL_APP_CLIENT_ID": "1v381ulabdhba86g8jltjv38uv"
    
};

